#define COMSIG_PHONE_SEND_DATA "phone_send_data"

#define CONSTATUS_NO_STATUS 1
#define CONSTATUS_CALLING 2
#define CONSTATUS_TIMEOUT 3
#define CONSTATUS_INITIALIZED 4
#define CONSTATUS_ENDED 5

#define PHONE_UNAVAILABLE 0
#define PHONE_AVAILABLE 1
